-- MySQL Script generated by MySQL Workbench
-- 07/28/17 15:51:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shoeshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shoeshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoeshop` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `shoeshop` ;

-- -----------------------------------------------------
-- Table `shoeshop`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `cate_name` VARCHAR(50) NOT NULL,
  `cate_parent` INT NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `cus_code` VARCHAR(100) NOT NULL,
  `cus_fname` VARCHAR(50) NOT NULL,
  `cus_lname` VARCHAR(50) NOT NULL,
  `cus_email` VARCHAR(100) NOT NULL,
  `cus_password` VARCHAR(250) NOT NULL,
  `cus_phone` VARCHAR(45) NOT NULL,
  `cus_address` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idCustomer`),
  UNIQUE INDEX `cus_code_UNIQUE` (`cus_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Bill` (
  `idBill` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NOT NULL,
  `bill_address` VARCHAR(250) NOT NULL,
  `bill_date` DATETIME NOT NULL,
  `bill_delivery_date` DATETIME NOT NULL,
  `bill_phone` VARCHAR(45) NOT NULL,
  `bill_status` TINYINT(1) NOT NULL DEFAULT 0,
  `bill_total` DOUBLE NOT NULL,
  PRIMARY KEY (`idBill`),
  INDEX `fk_Bill_Customer1_idx` (`idCustomer` ASC),
  CONSTRAINT `fk_Bill_Customer1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `shoeshop`.`Customer` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Producer` (
  `idProducer` INT NOT NULL AUTO_INCREMENT,
  `producer_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProducer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NOT NULL,
  `idProducer` INT NOT NULL,
  `pro_code` VARCHAR(45) NOT NULL,
  `pro_name` VARCHAR(100) NOT NULL,
  `pro_price` DOUBLE NOT NULL,
  `pro_discount` DOUBLE NOT NULL DEFAULT 0,
  `pro_description` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idProduct`),
  UNIQUE INDEX `pro_code_UNIQUE` (`pro_code` ASC),
  INDEX `fk_Product_Producer1_idx` (`idProducer` ASC),
  CONSTRAINT `fk_Product_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `shoeshop`.`Category` (`idCategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_Producer1`
    FOREIGN KEY (`idProducer`)
    REFERENCES `shoeshop`.`Producer` (`idProducer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Bill_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Bill_Details` (
  `idBill` INT NOT NULL,
  `idProduct` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idBill`, `idProduct`),
  INDEX `fk_Bill_Details_Product2_idx` (`idProduct` ASC),
  CONSTRAINT `fk_Bill_Details_Bill1`
    FOREIGN KEY (`idBill`)
    REFERENCES `shoeshop`.`Bill` (`idBill`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Bill_Details_Product2`
    FOREIGN KEY (`idProduct`)
    REFERENCES `shoeshop`.`Product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Size` (
  `idSize` INT NOT NULL AUTO_INCREMENT,
  `size_number` INT NOT NULL,
  PRIMARY KEY (`idSize`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Product_Details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Product_Details` (
  `idProduct` INT NOT NULL,
  `idSize` INT NOT NULL,
  PRIMARY KEY (`idProduct`, `idSize`),
  INDEX `fk_Product_Details_Size1_idx` (`idSize` ASC),
  CONSTRAINT `fk_Product_Details_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `shoeshop`.`Product` (`idProduct`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_Details_Size1`
    FOREIGN KEY (`idSize`)
    REFERENCES `shoeshop`.`Size` (`idSize`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shoeshop`.`Image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoeshop`.`Image` (
  `idImage` INT NOT NULL AUTO_INCREMENT,
  `idProduct` INT NOT NULL,
  `image_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idImage`, `idProduct`),
  INDEX `fk_Image_Product1_idx` (`idProduct` ASC),
  CONSTRAINT `fk_Image_Product1`
    FOREIGN KEY (`idProduct`)
    REFERENCES `shoeshop`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
